.TH slingshot-launcher 1 "Jul 21, 2014"
.SH NAME
slingshot\-launcher \- Application launcher for Pantheon
.SH "DESCRIPTION"
\fBSlingshot\fP is an application launcher for Pantheon, written in Vala and utilizing GTK+ and Cairo\.
It features an optional category view and fast application search that uses Synapse as a back-end\.
.SH SYNOPSIS
.B slingshot-launcher [OPTION...]
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit
.TP
.BR \-v ", " \-\-version
Print version info and exit
.TP
.BR \-s ", " \-\-silent
Launch Slingshot as a background process without it appearing visually
.TP
.BR \-c ", " \-\-command\-mode
Not implemented yet
.TP
.BR \-\-display\=\fIDISPLAY\fR
X display to use
.SH AUTHOR
Slingshot was written by Maxwell Barvian <maxwell@elementaryos.org>,
Giulio Collura <random.cpp@gmail.com>,
Andrea Basso <andrea@elementaryos.org>,
Akshay Shekher <akshay@elementaryos.org> et al.
.PP
This manual page was written by Sergey "Shnatsel" Davidoff <sergey@elementaryos.org>,
for the Debian project (but may be used by others).
